version: 0.1
phases:
  install:
    commands:
      - npm install time
      - npm install
      - cd src; npm install; cd ..
      - node run_zip
      - aws s3 cp billing.zip s3://sgas.sam.aws-services-billing
      - aws s3 cp swagger.yaml s3://sgas.sam.aws-services-billing
      - aws cloudformation package
         --template-file template.swagger.yaml
         --s3-bucket sgas.sam.aws-services-billing
         --output-template-file samTemplate.yaml
artifacts:
  type: zip
  files:
    - samTemplate.yaml
