AWSTemplateFormatVersion: "2010-09-09"
Outputs:
 DBSecurityGroupId:
  Value: !Ref DBSecurityGroup
 DBAccessorSecurityGroupId:
  Value: !Ref DBAccessorSecurityGroup
Parameters:
 NameTag:
  Type: String
  Default: ReplicationBlog
  AllowedPattern: "[\\x20-\\x7E]*"
  MaxLength: 255
  MinLength: 1
  Description: "Set the name tag for resources."
  ConstraintDescription: "can contain only ASCII characters."
 VpcId:
  Type: "AWS::EC2::VPC::Id"
Resources:
 DBSecurityGroup:
  Type: "AWS::EC2::SecurityGroup"
  Properties:
   GroupDescription: DBSecurityGroup
   VpcId: !Ref VpcId
   Tags:
    -
     Key: Name
     Value: !Join
       - "."
       - - !Ref NameTag
         - "rds.sg"
 DBAccessorSecurityGroup:
  Type: "AWS::EC2::SecurityGroup"
  Properties:
   GroupDescription: DBAccessorSecurityGroup
   VpcId: !Ref VpcId
   Tags:
    -
     Key: Name
     Value: !Join
       - "."
       - - !Ref NameTag
         - "rds.accessor.sg"
 MySQLAccessorSecurityGroupIngress:
  Type: "AWS::EC2::SecurityGroupIngress"
  Properties:
   GroupId: !Ref DBAccessorSecurityGroup
   CidrIp: "0.0.0.0/0"
   FromPort: 22
   ToPort: 22
   IpProtocol: tcp
 MySQLSecurityGroupIngress:
  Type: "AWS::EC2::SecurityGroupIngress"
  Properties:
   GroupId: !Ref DBSecurityGroup
   SourceSecurityGroupId: !Ref DBAccessorSecurityGroup
   FromPort: 3306
   ToPort: 3306
   IpProtocol: tcp
